export const employeeData = [
  {
    id: 1,
    name: "John Smith",
    role: "Software Engineer",
    department: "Engineering",
    salary: 85000,
    joinDate: "2022-03-15",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    role: "Product Manager",
    department: "Product",
    salary: 95000,
    joinDate: "2021-08-22",
  },
  {
    id: 3,
    name: "Michael Chen",
    role: "UX Designer",
    department: "Design",
    salary: 78000,
    joinDate: "2023-01-10",
  },
  {
    id: 4,
    name: "Emily Davis",
    role: "Data Analyst",
    department: "Analytics",
    salary: 72000,
    joinDate: "2022-11-05",
  },
  {
    id: 5,
    name: "Robert Wilson",
    role: "DevOps Engineer",
    department: "Engineering",
    salary: 88000,
    joinDate: "2021-06-30",
  },
];
